<?php

return [
    "Il sole splende nel cielo azzurro",
    "I bambini giocano nel parco",
    "Il gatto dorme sul divano",
    "La mamma cucina una torta deliziosa",
    "Il treno parte dalla stazione",
    "Le foglie cadono dagli alberi in autunno",
    "Il mare è calmo e cristallino",
    "Gli uccelli cantano all'alba",
    "La neve copre le montagne in inverno",
    "I fiori sbocciano in primavera",
    "Il vento soffia tra i rami",
    "La luna illumina la notte",
    "Le stelle brillano nel cielo notturno",
    "Il fuoco scoppietta nel camino",
    "La pioggia batte sui vetri",
    "L'arcobaleno appare dopo il temporale",
    "Il profumo del caffè riempie la cucina",
    "Le api ronzano tra i fiori",
    "Il cane abbaia al postino",
    "I pesci nuotano nell'acquario",
    "La bicicletta è parcheggiata nel cortile",
    "Il libro giace aperto sul tavolo",
    "La musica suona dolcemente in sottofondo",
    "Il telefono squilla nel silenzio",
    "La farfalla si posa su un fiore",
    "L'orologio ticchetta sul comodino",
    "Il computer si accende con un ronzio",
    "La televisione trasmette il telegiornale",
    "La radio diffonde le ultime notizie",
    "Il frigorifero ronza in cucina",
    "La lavatrice centrifuga i panni",
    "Il forno cuoce una pizza profumata",
    "La doccia gocciola lentamente",
    "Lo specchio riflette la luce del sole",
    "La porta cigola sui cardini",
    "Il pavimento scricchiola sotto i passi",
    "La finestra si appanna con il freddo",
    "Il tappeto ammortizza i passi",
    "La tenda ondeggia alla brezza",
    "Il quadro pende storto sulla parete",
    "La lampada illumina la stanza",
    "Il cuscino è morbido sulla poltrona",
    "La coperta scalda nelle notti fredde",
    "Il ventilatore gira silenziosamente",
    "L'aspirapolvere ronza sul tappeto",
    "La sveglia suona al mattino",
    "Il campanello trilla alla porta",
    "La penna scorre sulla carta",
    "La matita lascia un segno grigio",
    "La gomma cancella gli errori",
    "Il righello misura con precisione",
    "Le forbici tagliano la carta",
    "La colla incolla i pezzi",
    "Il nastro adesivo sigilla la scatola",
    "La graffetta tiene insieme i fogli",
    "La pinzatrice fissa i documenti",
    "L'evidenziatore sottolinea le parole importanti",
    "La calcolatrice fa i conti",
    "Il calendario segna i giorni",
    "L'agenda annota gli impegni",
    "Il post-it ricorda le cose da fare",
    "La busta contiene una lettera",
    "Il francobollo è incollato sull'angolo",
    "L'indirizzo è scritto con cura",
    "Il mittente firma la lettera",
    "Il destinatario apre la busta",
    "Il timbro marca la data",
    "La cartolina arriva da lontano",
    "L'email ping nel computer",
    "Il messaggio appare sullo schermo",
    "L'allegato si scarica lentamente",
    "La password protegge l'account",
    "Il virus infetta il sistema",
    "L'antivirus scansiona i file",
    "Il firewall blocca gli accessi non autorizzati",
    "Il backup salva i dati importanti",
    "Il cloud sincronizza i dispositivi",
    "Lo smartphone vibra in tasca",
    "Il tablet si ricarica sul comodino",
    "L'auricolare trasmette la musica",
    "La fotocamera cattura il momento",
    "Il microfono registra la voce",
    "L'altoparlante diffonde il suono",
    "La batteria si scarica velocemente",
    "Il caricabatterie si collega alla presa",
    "La memoria si riempie di foto",
    "L'app si aggiorna automaticamente",
    "Il GPS indica la direzione",
    "Il Wi-Fi connette alla rete",
    "Il Bluetooth accoppia i dispositivi",
    "La notifica pop sullo schermo",
    "L'emoticon esprime un'emozione",
    "L'hashtag raggruppa i contenuti",
    "Il link porta a una nuova pagina",
    "Il cookie memorizza le preferenze",
    "Il captcha verifica l'utente umano",
    "L'avatar rappresenta l'utente online"
];
